# workflow to run tests (i.e. jest) on PR
name: jest
on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # Setup npm environment to run tests
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run test
